spring:
 redis:
   host: localhost
   port: 6379
   #password:
   lettuce:
     pool:
       max-active: 30
 datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
   username: root
   password: root123



mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  #mapper-locations: classpath:/com/vajun./admin/mmapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  #typeAliasesPackage: com.vajun.admin.**.entity
  #扫描枚举
  #typeEnumsPackage:
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_null
      #驼峰下划线转换
      #column-underline: false
      #数据库大写下划线转换
      #      capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    #配置控制台打印完整带参数SQL语句。SqlInterceptor 方法打印替换占位符后的完整Sql
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    database-id: mysql

# 屏蔽安全验证
management:
  endpoints:
    web:
      exposure:
        include: '*'  # 可以选择【"health","mappings","bus-refresh"】三种选项暴露那些端点
logging:
  config: classpath:log/logback-spring.xml


